# Generated by Codex on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
