# Generated by Codex on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=True),
        ),
    ]
