# Generated by Django 6.0.4 on 2026-04-21 21:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled_currencies',
            field=models.JSONField(blank=True, default=accounts.models.default_enabled_currencies),
        ),
        migrations.AddField(
            model_name='user',
            name='exchange_rates',
            field=models.JSONField(blank=True, default=dict, help_text='Currency -> rate to base currency.'),
        ),
    ]
