# Generated by Django 6.0.3 on 2026-05-10 16:12

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staff_login_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='permissions',
            field=models.JSONField(blank=True, default=accounts.models.default_staff_permissions),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('key_prefix', models.CharField(db_index=True, max_length=24)),
                ('key_hash', models.CharField(max_length=128)),
                ('permissions', models.JSONField(blank=True, default=accounts.models.default_api_key_permissions)),
                ('status', models.CharField(choices=[('active', 'active'), ('revoked', 'revoked')], default='active', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
