# Generated by Django 6.0.4 on 2026-09-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_google_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_pending',
            field=models.BooleanField(default=False),
        ),
    ]
