# Generated by Django 6.0.4 on 2026-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_retire_assistant_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='launch_promo_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='launch_promo_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
