# Generated by Django 6.0.3 on 2026-04-07 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed')], default='in_progress', max_length=20)),
                ('items_counted', models.PositiveIntegerField(default=0)),
                ('discrepancies_found', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expected_stock', models.IntegerField()),
                ('actual_stock', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('status', models.CharField(choices=[('unresolved', 'unresolved'), ('investigating', 'investigating'), ('resolved', 'resolved')], default='unresolved', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='audits.audit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inventory.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('counted_quantity', models.IntegerField()),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='audits.audit')),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
