# Generated by Django 6.0.3 on 2026-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_debt_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='type',
            field=models.CharField(choices=[('add', 'add'), ('redeem', 'redeem'), ('debt', 'debt'), ('payment', 'payment'), ('writeoff', 'writeoff')], max_length=20),
        ),
    ]
