FEATURE_GROUPS = {
    "starter": [
        "products",
        "customers",
        "users",
        "basic_sales",
        "daily_summaries",
        "pwa_access",
        "basic_expenses",
        "reports",
        "onboarding_checklist",
        "usage_indicators",
    ],
    "growth": [
        "barcode_scanning",
        "audits",
        "alerts",
        "discrepancy_tracking",
        "qr_loyalty",
        "advanced_reports",
        "whatsapp_reports",
        "rule_insights",
        "reorder_suggestions",
    "command_assistant",
    "receipt_scan_simulator",
    "receipt_ocr",
    "ai_assistant",
    ],
    "business": [
        "role_based_access",
        "offline_sync",
        "bulk_import_export",
        "advanced_analytics",
        "forecasting",
        "staff_activity_logs",
        "multi_branch",
        "automation_rules",
        "excel_exports",
        "api_access",
        "custom_reports",
        "background_audits",
    ],
}

FEATURE_METADATA = {
    "products": {"label": "Product limit", "plan": "starter", "category": "Core"},
    "customers": {"label": "Customer limit", "plan": "starter", "category": "Core"},
    "users": {"label": "User limit", "plan": "starter", "category": "Core"},
    "basic_sales": {"label": "Basic sales", "plan": "starter", "category": "Core"},
    "daily_summaries": {"label": "Daily summaries", "plan": "starter", "category": "Core"},
    "pwa_access": {"label": "PWA/mobile access", "plan": "starter", "category": "Core"},
    "basic_expenses": {"label": "Basic expense logging", "plan": "starter", "category": "Core"},
    "reports": {"label": "Simple reports", "plan": "starter", "category": "Core"},
    "onboarding_checklist": {"label": "Onboarding checklist", "plan": "starter", "category": "Guidance"},
    "usage_indicators": {"label": "Usage indicators", "plan": "starter", "category": "Guidance"},
    "barcode_scanning": {"label": "Barcode scanning", "plan": "starter", "category": "Operations"},
    "audits": {"label": "Inventory audits", "plan": "growth", "category": "Operations"},
    "alerts": {"label": "Low-stock alerts", "plan": "growth", "category": "Operations"},
    "discrepancy_tracking": {"label": "Discrepancy tracking", "plan": "growth", "category": "Operations"},
    "qr_loyalty": {"label": "QR loyalty", "plan": "growth", "category": "Customers"},
    "advanced_reports": {"label": "Reports with charts", "plan": "growth", "category": "Reports"},
    "whatsapp_reports": {"label": "WhatsApp-ready summaries", "plan": "growth", "category": "Reports"},
    "rule_insights": {"label": "Rule-based insights", "plan": "growth", "category": "Insights"},
    "reorder_suggestions": {"label": "Automatic reorder suggestions", "plan": "growth", "category": "Insights"},
    "command_assistant": {"label": "Command assistant", "plan": "growth", "category": "Assistant"},
    "receipt_scan_simulator": {"label": "Receipt scan simulator", "plan": "growth", "category": "Expenses"},
    "receipt_ocr": {"label": "Receipt OCR", "plan": "growth", "category": "Expenses"},
    "ai_assistant": {"label": "AI/Admin Assistance System", "plan": "growth", "category": "Assistant"},
    "role_based_access": {"label": "Role-based access", "plan": "business", "category": "Control"},
    "offline_sync": {"label": "Offline auto-sync", "plan": "business", "category": "Control"},
    "bulk_import_export": {"label": "Bulk import/export", "plan": "business", "category": "Control"},
    "advanced_analytics": {"label": "Advanced analytics", "plan": "business", "category": "Analytics"},
    "forecasting": {"label": "Forecasting", "plan": "business", "category": "Analytics"},
    "custom_reports": {"label": "Custom reports", "plan": "business", "category": "Reports"},
    "background_audits": {"label": "Background audits", "plan": "business", "category": "Automation"},
    "staff_activity_logs": {"label": "Staff activity logs", "plan": "business", "category": "Control"},
    "multi_branch": {"label": "Multi-branch controls", "plan": "business", "category": "Control"},
    "automation_rules": {"label": "Automation rules", "plan": "business", "category": "Automation"},
    "excel_exports": {"label": "Excel exports", "plan": "business", "category": "Reports"},
    "api_access": {"label": "API access", "plan": "business", "category": "Integrations"},
}
