# Generated by Django 6.0.4 on 2026-04-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchaseorder_purchaseorderitem_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_currency',
            field=models.CharField(default='ZAR', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_fx_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='ZAR', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='fx_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_cost_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='line_total_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_cost_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
