# Generated by Django 6.0.3 on 2026-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_barcodelookupcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodelookupcache',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='supplier',
            name='reliability_score',
            field=models.PositiveSmallIntegerField(default=80),
        ),
    ]
