# Generated by Django 6.0.4 on 2026-09-15 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_barcodelookupcache_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('request_id', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('incoming', 'incoming'), ('outgoing', 'outgoing')], max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('partial', 'partial'), ('paid', 'paid')], max_length=10)),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_category', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('fx_rate_to_base', models.DecimalField(decimal_places=6, max_digits=18)),
                ('movement_date', models.DateField()),
                ('movement_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'request_id'), name='unique_supply_request')],
            },
        ),
    ]
