# Generated by Django 6.0.4 on 2026-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_invoice_number_sale_receipt_number_tillsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_currency',
            field=models.CharField(default='ZAR', max_length=10),
        ),
    ]
