# Generated by Django 6.0.4 on 2026-04-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncconflict',
            name='action_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='action_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='resolution_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('resolved', 'resolved'), ('ignored', 'ignored')], default='open', max_length=20),
        ),
    ]
