# Generated by Django 6.0.4 on 2026-04-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='ZAR', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='fx_rate_to_base',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
